import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import { Suspense } from "react"; // 1. Import Suspense
import GoogleTagManager from "./components/GoogleTagManager"; // 2. Import your GTM component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jia Pixel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* The <head> tag is automatically populated by Next.js from your metadata */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 3. Add the GTM component wrapped in Suspense here */}
        <Suspense fallback={null}>
          <GoogleTagManager />
        </Suspense>
        
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}